config:
  project_repos:
    o3skim:
      repo: 'https://git.scc.kit.edu/synergy.o3as/o3skim.git'
      branch: master 

sqa_criteria:
  qc_style:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - stylecheck
  qc_functional:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
              - functional
  qc_security:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - bandit
  qc_doc:
    repos:
      o3skim:
        container: testing
        tox:
          tox_file: /o3skim/tox.ini
          testenv:
            - docs

#environment:
#  LANG: C.UTF-8

timeout: 900
